# TASCA 4: PRÁCTICA CON PROGRAMACIÓN NUMÉRICA

___EJERCICIO 1___

In [68]:
from numpy import random
import numpy as np

#CREACION DE ARRAY
arr = np.random.rand(5)

#RESUMEN ESTADISTICO
print('Nuestra Array es:', arr)
print('media:', np.around(np.mean(arr),4), 'mediana:', np.around(np.median(arr),4), 'sd:', np.around(np.std(arr),4))
print('var:', np.around(np.var(arr),4), 'cov:', np.around(np.cov(arr),4), 'correlación:', np.around(np.corrcoef(arr),4))

# CONFIRMACION DE LA DIMENSION DE LA ARRAY
if arr.ndim > 1:
    print("ERROR: la array tiene más de una dimensión")
else:
    print("La Array es de 1 dimensión")

Nuestra Array es: [0.53031011 0.85223465 0.25728147 0.8887182  0.90648534]
media: 0.687 mediana: 0.8522 sd: 0.2551
var: 0.0651 cov: 0.0813 correlación: 1.0
La Array es de 1 dimensión


___EJERCICIO 2___

In [69]:
# CREACION DE CUADRADO NXN
x = random.randint(100, size=(3, 3))

print(x)

[[49 31 75]
 [59 31 65]
 [18 84 80]]


___EJERCICO 3___

In [70]:
# TABLA DE DOS DIMENSIONES
tabla = random.randint(50, size=(2,3))
print('Tabla 2D: ', tabla)

#SUMA DE FILAS Y COLUMNAS
sum_col = np.sum([tabla], axis= 1)
suma_filas = np.sum([tabla], axis= 2)

print('El total de cada columna es: ' , sum_col)
print('El total de cada filas es: ' , sum_filas)


Tabla 2D:  [[ 6  1 44]
 [12 39 22]]
El total de cada columna es:  [[18 40 66]]
El total de cada filas es:  [[88 52]]


___EJERCICIO 4___

In [76]:
#FORMULA DE CORRELACION

correlacion = np.around(np.corrcoef(arr),4)

print(correlacion)

if correlacion == 0:
    print('No hay asociación entre las variables')
elif correlacion <= 1:
    print('Hay una correlación positiva')
else:
    print('Hay una correlación negativa')

1.0
Hay una correlación positiva
